flowchart TD

A[👤 Usuário]

A --> B[🤖 TechHelp Copilot]

B --> C{Identificar intenção}

C --> D[🌐 Internet]

C --> E[💻 Computador]

C --> F[📦 Instalação]

C --> G[👨 Atendimento Humano]

D --> H[🧠 IA Generativa]

E --> H

F --> H

H --> I[✅ Resposta ao usuário]